#
# Macro file for the initialization phase of "inducedFission.cc"
#
# Sets some default verbose
# and initializes the graphic.
#
/control/verbose 0
/tracking/verbose 0
/event/verbose 0
/run/verbose 0


/tracking/storeTrajectory 0
/run/initialize

#/gps/particle neutron
#/gps/pos/type Beam # Point
#/gps/pos/shape Circle
#/gps/position 0.0 0.0 -1.0 cm
#/gps/pos/centre 0.0 0.0 -1.0 cm
#/gps/pos/radius 10.0 mm
#/gps/direction 0 0 +1
#/gps/ang/type beam1d # cos
#/gps/ene/type Gauss
#/gps/ene/mono 3.0 MeV
#/gps/ene/sigma 0.2 keV

/analysis/setFileName indFiss
#/analysis/H1/SetActivationToAll true

/gun/particle neutron
/gun/energy 3.0 MeV
/gun/position 0.0 0.0 -1.0 cm
/run/beamOn 10000
