#=========================================
#   Neutron spallation
#=========================================
/control/verbose 0
/tracking/verbose 0
/event/verbose 0
/run/verbose 0
/gps/verbose 0 #2

/tracking/storeTrajectory 0

/run/initialize

#### Default intensity say 1
#/gps/source/intensity 1

#### fix gps source particle and type
/gps/particle proton
/gps/pos/type Beam

#### incident surface is in X-Y plane
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 1 0

#### Beam spot is centred at (0 0 -1800)1D Gaussian shape with 10 mm central plateau
/gps/pos/shape Circle
/gps/position 0.0 0.0 -1800.0 mm       #  1200 mm length of beam pipe at 0, 0, -900
/gps/pos/radius 10.0 mm
/gps/pos/sigma_r 0.1 mm

#### Beam is travelling along +Z axis with 1 degree dispersion
/gps/ang/type beam1d
/gps/ang/sigma_r 0.5 deg
/gps/direction 0 0 1
#/gps/ang/rot2  0  1  0
#/gps/ang/rot1 -1  0  0

#### Beam energy is in gaussian profile  with 1 keV dispersion
/gps/ene/type Gauss
/gps/ene/mono 1.73 GeV   # 2.5 GeV/c
#/gps/ene/mono 3.62 GeV   # 3.5 GeV/c
#/gps/ene/mono 1.0 GeV
/gps/ene/sigma 0.5 keV

####
#/tarc/beam/DefaultBeamPosition false
#/tarc/histo/fileName Hadro
#/tarc/histo/setHisto 0 10  0 1500 MeV

/run/beamOn 1

