#
# Macro file for the initialization phase of "muonLife.cc"
#
# Sets some default verbose
# and initializes the graphic.
#
/vis/verbose errors
/control/verbose 0
/tracking/verbose 0
/event/verbose 0
/run/verbose 0
#
/run/initialize
#
/vis/scene/create
#
#
# Use this open statement to create an OpenGL view:
/vis/open OGL 1020x700-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Draw geometry:
/vis/drawVolume
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
#
# Specify view angle:
# 88 8  : rot Y, X is out of screen
# 88 88 : rot Z, Y is out of screen
# 8 88  : rot X, Z is out of screen
# 8 8   : X is right, Y is nearly vertical
/vis/viewer/set/viewpointThetaPhi   88 8 #35 50
/vis/sceneHandler/attach
# Specify zoom value:
/vis/viewer/zoom 1.4
#
# Hidden edge removal
/vis/viewer/set/hiddenEdge 0
# Specify style (surface or wireframe):
#/vis/viewer/set/style surface
/vis/viewer/set/style wireframe
# To get nice view
/vis/geometry/set/visibility World 0 false
#
/vis/viewer/flush
# Draw coordinate axes:
/vis/scene/add/axes 0 0 0 70 cm
#
/vis/scene/add/userAction
/vis/ogl/set/displayListLimit 100000000000
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts false
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set alpha blue
/vis/modeling/trajectories/drawByParticleID-0/set GenericIon blue
#
# To superimpose all of the events from a given run:
# /vis/scene/endOfEventAction accumulate 10000000
#/vis/scene/endOfEventAction accumulate 0
/tracking/storeTrajectory 0
/vis/scene/add/trajectories smooth
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
/vis/viewer/update

#/gps/particle neutron
#/gps/pos/type Beam # Point
#/gps/pos/shape Circle
#/gps/pos/rot1 1 0 0
#/gps/pos/rot2 0 1 0
#/gps/position 0. 0. -1. cm
#/gps/pos/radius 10.0 mm
#/gps/direction 0. 0. 1.
#/gps/ang/type beam1d # cos
#/gps/ene/mono 3.0 MeV
#/gps/ene/min 2.5 MeV
#/gps/ene/max 7.0 MeV

#/globalField/setValue 0.0 1.0 0.0 tesla

/gun/particle mu+
/gun/energy 4.0 GeV
/gun/position 0.0 500.0 0.0 mm
/gun/direction 0.0 -1.0 0.0

/run/beamOn 100000

